#pragma once

#define MODCHIP_CMD_DISABLE_NEXT_OSDSYS_HOOK 0x1c615a6d
#define MODCHIP_CMD_GET_EE_STAGE1_SIZE 0xd0085c2f
#define MODCHIP_CMD_GET_EE_STAGE2_SIZE 0xc46e1e45
#define MODCHIP_CMD_GET_EE_STAGE2 0x882c2315
#define MODCHIP_CMD_READ_APP 0x0a6c2278
#define MODCHIP_CMD_KV_GET 0x1d271ab7
#define MODCHIP_CMD_KV_SET 0x40b133eb

enum
{
    MODCHIP_SETTINGS_MENU_AUTOBOOT = 0,
    MODCHIP_SETTINGS_MENU_AUTOBOOT_DELAY = 1,
    MODCHIP_SETTINGS_MENU_AUTOBOOT_ITEM_IDX = 2,
    MODCHIP_SETTINGS_MENU_OSDSYS_SETTINGS = 3,
    MODCHIP_SETTINGS_KEYS_TOTAL,
};
